version: '3.6'
services:
  #NGINX
  web:
    image: nginx
#    ports:
#      - "8080:80"
#    environment:
#      - NGINX_HOST=foobar.com
#      - NGINX_PORT=80
  #BD
  db:
    image: postgres
    restart: always
    environment:
      - DB_USER=devops
      - DB_PASS=123
      - DB_NAME=devops_db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8081"
    command: "npm start"
  redis:
    image: "redis:alpine"
volumes:
  http:
